import { defineConfig } from "tinacms";

export default defineConfig({
  branch: "main",
  clientId: process.env.TINA_CLIENT_ID,
  token: process.env.TINA_TOKEN,
  build: {
    outputFolder: "admin",
    publicFolder: ".",
  },
  schema: {
    collections: [
      {
        name: "site",
        label: "Website teksten",
        path: "src/_data",
        format: "json",
        match: {
          include: "site",
        },
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "object",
            name: "bedrijf",
            label: "Bedrijfsgegevens",
            fields: [
              { type: "string", name: "naam", label: "Bedrijfsnaam" },
              { type: "string", name: "slogan", label: "Slogan" },
              { type: "string", name: "telefoon", label: "Telefoonnummer (zoals getoond, bv. 06-19421856)" },
              { type: "string", name: "telefoon_href", label: "Telefoonnummer (voor de belknop, alleen cijfers)" },
              { type: "string", name: "email", label: "E-mailadres" },
              { type: "string", name: "straat", label: "Straat en huisnummer" },
              { type: "string", name: "postcode_plaats", label: "Postcode en plaats" },
              { type: "string", name: "openingstijden", label: "Openingstijden" },
            ],
          },
          {
            type: "object",
            name: "navigatie",
            label: "Menu (bovenin de website)",
            fields: [
              { type: "string", name: "home", label: "\"Home\"" },
              { type: "string", name: "over_ons", label: "\"Over mij\"" },
              { type: "string", name: "diensten", label: "\"Diensten\"" },
              { type: "string", name: "contact", label: "\"Contact\"" },
              { type: "string", name: "cta_knop", label: "Knop rechtsboven" },
            ],
          },
          {
            type: "object",
            name: "home",
            label: "Home",
            fields: [
              { type: "string", name: "hero_titel", label: "Hoofdtitel (hero)" },
              { type: "string", name: "hero_ondertitel", label: "Ondertitel (hero)", ui: { component: "textarea" } },
              { type: "string", name: "hero_knop", label: "Knoptekst (hero)" },
              { type: "string", name: "intro_titel", label: "Titel \"Welkom\"-sectie" },
              { type: "string", name: "intro_tekst", label: "Tekst \"Welkom\"-sectie", ui: { component: "textarea" } },
              { type: "string", name: "diensten_titel", label: "Titel \"Diensten\"-sectie" },
              { type: "string", name: "diensten_tekst", label: "Tekst \"Diensten\"-sectie", ui: { component: "textarea" } },
              { type: "string", name: "diensten_knop", label: "Knoptekst \"Diensten\"-sectie" },
              { type: "string", name: "over_titel", label: "Titel \"Over Annabelle\"-sectie" },
              { type: "string", name: "over_tekst", label: "Tekst \"Over Annabelle\"-sectie", ui: { component: "textarea" } },
              { type: "string", name: "over_knop", label: "Knoptekst \"Over Annabelle\"-sectie" },
              { type: "string", name: "voor_wie_titel", label: "Titel \"Ook voor organisaties\"" },
              { type: "string", name: "voor_wie_tekst", label: "Tekst \"Ook voor organisaties\"", ui: { component: "textarea" } },
              { type: "string", name: "cta_titel", label: "Titel afsluitende oproep" },
              { type: "string", name: "cta_tekst", label: "Tekst afsluitende oproep", ui: { component: "textarea" } },
              { type: "string", name: "cta_knop", label: "Knoptekst afsluitende oproep" },
            ],
          },
          {
            type: "object",
            name: "over_ons",
            label: "Over mij",
            fields: [
              { type: "string", name: "titel", label: "Titel" },
              { type: "string", name: "intro", label: "Introzin", ui: { component: "textarea" } },
              { type: "string", name: "paragraaf_1", label: "Paragraaf 1", ui: { component: "textarea" } },
              { type: "string", name: "paragraaf_2", label: "Paragraaf 2", ui: { component: "textarea" } },
              { type: "string", name: "paragraaf_3", label: "Paragraaf 3", ui: { component: "textarea" } },
              { type: "string", name: "missie_titel", label: "Titel missie" },
              { type: "string", name: "missie_tekst", label: "Tekst missie", ui: { component: "textarea" } },
              { type: "string", name: "cta_titel", label: "Titel afsluitende oproep" },
              { type: "string", name: "cta_knop", label: "Knoptekst afsluitende oproep" },
            ],
          },
          {
            type: "object",
            name: "diensten",
            label: "Diensten",
            fields: [
              { type: "string", name: "titel", label: "Titel" },
              { type: "string", name: "intro", label: "Introzin", ui: { component: "textarea" } },
              {
                type: "object",
                name: "pakket_1",
                label: "Pakket 1",
                fields: [
                  { type: "string", name: "naam", label: "Naam" },
                  { type: "string", name: "prijs", label: "Prijs" },
                  { type: "string", name: "beschrijving", label: "Beschrijving", ui: { component: "textarea" } },
                  { type: "string", name: "items", label: "Onderdelen van dit pakket", list: true },
                ],
              },
              {
                type: "object",
                name: "pakket_2",
                label: "Pakket 2",
                fields: [
                  { type: "string", name: "naam", label: "Naam" },
                  { type: "string", name: "prijs", label: "Prijs" },
                  { type: "string", name: "beschrijving", label: "Beschrijving", ui: { component: "textarea" } },
                  { type: "string", name: "items", label: "Onderdelen van dit pakket", list: true },
                ],
              },
              { type: "string", name: "op_maat_titel", label: "Titel \"Altijd op maat\"" },
              { type: "string", name: "op_maat_tekst", label: "Tekst \"Altijd op maat\"", ui: { component: "textarea" } },
              { type: "string", name: "doelgroepen_titel", label: "Titel \"Ook voor professionals\"" },
              { type: "string", name: "doelgroepen_tekst", label: "Tekst \"Ook voor professionals\"", ui: { component: "textarea" } },
              { type: "string", name: "cta_titel", label: "Titel afsluitende oproep" },
              { type: "string", name: "cta_tekst", label: "Tekst afsluitende oproep", ui: { component: "textarea" } },
              { type: "string", name: "cta_knop", label: "Knoptekst afsluitende oproep" },
            ],
          },
          {
            type: "object",
            name: "contact",
            label: "Contact",
            fields: [
              { type: "string", name: "titel", label: "Titel" },
              { type: "string", name: "intro", label: "Introzin", ui: { component: "textarea" } },
              { type: "string", name: "formulier_titel", label: "Titel formulier" },
              { type: "string", name: "label_naam", label: "Label \"Naam\"-veld" },
              { type: "string", name: "label_email", label: "Label \"E-mailadres\"-veld" },
              { type: "string", name: "label_telefoon", label: "Label \"Telefoonnummer\"-veld" },
              { type: "string", name: "label_bericht", label: "Label \"Bericht\"-veld" },
              { type: "string", name: "knop_verzenden", label: "Knoptekst versturen" },
              { type: "string", name: "gegevens_titel", label: "Titel \"Contactgegevens\"" },
              { type: "string", name: "kaart_titel", label: "Titel kaart" },
            ],
          },
          {
            type: "object",
            name: "footer",
            label: "Footer",
            fields: [
              { type: "string", name: "tekst", label: "Tekst", ui: { component: "textarea" } },
              { type: "string", name: "copyright", label: "Auteursrecht-tekst" },
            ],
          },
        ],
      },
    ],
  },
});
